name: CI
on: issue_comment 

jobs:     
  debug:
    runs-on: ubuntu-latest
    steps:

    - name: see payload
      run: echo "$PAYLOAD"
      env:
        PAYLOAD: ${{ toJSON(github.event) }}

    - uses: actions/upload-artifact@v2
      with:
        name: webhook
        path: ${{ github.event_path }}
  
  comment:
    runs-on: ubuntu-latest
    steps:
    - name: Copy Repository Contents
      uses: actions/checkout@master
